name: Build fonts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - font: pragmasevka
          - font: iosevka-comfy
          - font: iosevka-comfy-wide
          - font: iosevka-comfy-wide-fixed
          - font: iosevka-comfy-wide-duo
          - font: iosevka-comfy-motion
          - font: iosevky-comfy-motion-fixed
          - font: iosevka-comfy-motion-duo
          - font: iosevka-comfy-fixed
          - font: iosevka-comfy-duo

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build the image
        run: docker build -t iosevka_build . -f Dockerfile
      - name: Remove old build
        run: rm -rf dist
      - name: Build fonts
        run: docker run -v $(pwd):/build iosevka_build ttf::${{ matrix.font }}
      - name: Upload the files
        uses: actions/upload-artifact@v2
        with:
          name: "$font"
          path: "dist/"
